# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- powershell: Install-Module Pester -Scope CurrentUser -Force
  displayName: 'Install Pester for testing'

- powershell: ./scripts/Test.ps1
  displayName: 'Run Tests'
